name: CI

on: [release]

jobs:
  publish:
    name: list on nuget
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish NuGet
      uses: rohith/publish-nuget@v2.0.0
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: src/FluentPollingTriggerBuilder/FluentPollingTriggerBuilder.csproj
        # Regex (with version in a capturing group) to extract the version from `VERSION_FILE_PATH`
        VERSION_REGEX: <Version>(.*)<\/Version>
        # API key for the NuGet feed
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
